# Dependencies
markdown:         kramdown
highlighter:      none

# Permalinks
permalink:        pretty

# Setup
title:            Anish's Blog
tagline:          ''
description:      'Collection of my notes, ideas, and thoughts.'
url:              http://hyde.getpoole.com
baseurl:          /
social_links:
  - url: "https://www.linkedin.com/in/anayanapalli/"
    icon: "/public/icons/linkedin.png"
    alt: "LinkedIn"
  - url: "https://github.com/anayanapalli"
    icon: "/public/icons/github.png"
    alt: "GitHub"
  - url: "https://www.instagram.com/stoicanish/"
    icon: "/public/icons/instagram.png"
    alt: "Instagram"
  - url: "https://twitter.com/anayanapalli"
    icon: "/public/icons/twitter.png"
    alt: "Twitter"
  - url: "mailto:anayanapalli@gmail.com"
    icon: "/public/icons/gmail.png"
    alt: "Email"

author:
  name:           'Anish Nayanapalli'
  url:            https://twitter.com/anayanapalli

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate]
